### ISSUE TITLE
Instalation problem

### ISSUE THREAD

**Issue by ABaaaC** [musco-ai/musco-pytorch#9]
Recently, Pip changed its internal implementation.
So in the last pip versions, I met error with setup.py

it can be debugged by replacing
```
return [str(item.req) for item in requirements]
```
by
```
try:
    return [str(item.req) for item in requirements]
except:
    return [str(item.requirement) for item in requirements]
```
for compatible with both the versions.

source:
https://stackoverflow.com/questions/62114945/attributeerror-parsedrequirement-object-has-no-attribute-req

**Comment by juliagusak** [comment]
@ABaaaC, thank you for pointing out this problem! I've fixed it.

Best regards,
Julia
